import Head from "next/head";
import About from "~/components/sections/about";
import AboutUs from "~/components/sections/aboutUs";
import CarouselSection from "~/components/sections/carousel";
import Comment from "~/components/sections/comment";
import ContactUs from "~/components/sections/contactUs";
import FAQ from "~/components/sections/Faq";
import Feedbacks from "~/components/sections/feedbacks";
import Footer from "~/components/sections/footer";
import HeroSection from "~/components/sections/heroSection";
import Services from "~/components/sections/services";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ménage lik services</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <AboutUs />
      <div className="h-0 md:h-24"></div>
      <About />
      <Services />
      <Comment />
      <CarouselSection />
      <Feedbacks />
      <FAQ />
      <Footer />
    </>
  );
}
